import { sql } from "drizzle-orm";
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

// A plain string default (e.g. .default("CURRENT_TIMESTAMP")) is inserted
// literally by Drizzle -- it doesn't ask SQLite to evaluate anything. This
// wraps the raw SQL expression so the DB actually fills in the real time.
const now = sql`CURRENT_TIMESTAMP`;

export const adminUsers = sqliteTable("admin_users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  salt: text("salt").notNull(),
  name: text("name").notNull(),
  role: text("role").notNull().default("board_member"), // "tech_admin" | "president" | "vice_president" | "treasurer" | "board_member"
  position: text("position"), // free-text title (Vice President, Treasurer, etc.) -- display only, grants no access
  phone: text("phone"),
  createdAt: text("created_at").notNull().default(now),
  failedLoginCount: integer("failed_login_count").notNull().default(0),
  lockedUntil: integer("locked_until"), // epoch ms; login is blocked while this is in the future
});

// Shared, growable list of board titles (Vice President, Treasurer, etc.)
// offered in the Board Members "Title" dropdown. Presidents/tech admins can
// add to it; a member's actual title (admin_users.position) is still free
// text, so nothing breaks if this list doesn't have every title ever used.
export const positionOptions = sqliteTable("position_options", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  label: text("label").notNull().unique(),
});

// One-time links for setting up a new board member login or resetting a
// password. Whoever triggers this never sees the resulting password — only
// the person with access to that inbox can complete it.
export const passwordResetTokens = sqliteTable("password_reset_tokens", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  adminUserId: integer("admin_user_id").notNull(),
  token: text("token").notNull().unique(),
  expiresAt: integer("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(now),
});

export const sessions = sqliteTable("sessions", {
  id: text("id").primaryKey(),
  adminUserId: integer("admin_user_id").notNull(),
  expiresAt: integer("expires_at").notNull(),
});

export const pageSections = sqliteTable("page_sections", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  pageSlug: text("page_slug").notNull(),
  sectionKey: text("section_key").notNull(),
  heading: text("heading"),
  bodyHtml: text("body_html").notNull(),
  updatedAt: text("updated_at").notNull().default(now),
});

// Board-swappable copies of the site's handful of hard-coded images (nav
// logo/hero, range rules photo, matches flyer) -- keyed by a fixed logical
// name rather than autoincrement id, since each key corresponds to exactly
// one spot in the layout. No row for a key means "use the bundled default
// asset" (see lib/siteImages.ts), so nothing breaks before a board member
// ever uploads a replacement.
export const siteImages = sqliteTable("site_images", {
  key: text("key").primaryKey(),
  r2Key: text("r2_key").notNull(),
  fileName: text("file_name").notNull(),
  updatedAt: text("updated_at").notNull().default(now),
});

export const calendarEvents = sqliteTable("calendar_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  start: text("start").notNull(),
  color: text("color").notNull().default("#2c3e1f"),
  description: text("description"),
  imageR2Key: text("image_r2_key"),
  imageFileName: text("image_file_name"),
  documentR2Key: text("document_r2_key"),
  documentFileName: text("document_file_name"),
  linkUrl: text("link_url"),
  linkLabel: text("link_label"),
  createdAt: text("created_at").notNull().default(now),
  // Set only on events generated by the "Add a recurring series" admin tool --
  // every event from the same submission shares one seriesId, so the public
  // calendar can tell a recurring event from a one-off with the same title.
  seriesId: text("series_id"),
  // Plain-language description of the rule ("Every 2nd Saturday of the
  // month"), computed once at series-creation time (see lib/recurrence.ts).
  recurrenceLabel: text("recurrence_label"),
});

// Singleton row (id=1) controlling how large the public calendar grid renders --
// a preset dropdown in the admin CMS instead of a raw pixel value, since the
// audience is non-technical board members, not developers.
export const calendarSettings = sqliteTable("calendar_settings", {
  id: integer("id").primaryKey(),
  sizePreset: text("size_preset").notNull().default("comfortable"), // "compact" | "comfortable" | "large"
  updatedAt: text("updated_at").notNull().default(now),
});

// Singleton row (id=1) for the handful of nav-bar text bits board members can
// edit directly -- the club name and its subtitle, plus a size preset for
// that title text. Same "one editable settings row" pattern as
// calendarSettings above.
export const siteSettings = sqliteTable("site_settings", {
  id: integer("id").primaryKey(),
  navTitle: text("nav_title").notNull().default("Kiowa Gun Club"),
  navSubtitle: text("nav_subtitle").notNull().default("Great Bend, Kansas"),
  navTitleSize: text("nav_title_size").notNull().default("comfortable"), // "compact" | "comfortable" | "large"
  updatedAt: text("updated_at").notNull().default(now),
  // Idempotency guard for the annual Sept 10 termination sweep
  // (app/api/cron/renewal-termination) -- set to the year the sweep last
  // ran so the daily cron doesn't re-run it every day after the cutoff.
  lastTerminationSweepYear: integer("last_termination_sweep_year"),
});

export const matches = sqliteTable("matches", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  // Free text rather than an enum -- board members occasionally add a new
  // discipline and shouldn't need a code change to do it.
  discipline: text("discipline").notNull().default("Defensive Pistol"),
  eventDate: text("event_date").notNull(),
  eventTime: text("event_time").notNull(),
  notes: text("notes"),
  resultsUrl: text("results_url"),
  sortOrder: integer("sort_order").notNull().default(0),
});

// Photos scoped to a single match date, shown in that match's public gallery.
// Replaces the old 4 hardcoded images shared across the whole matches page.
export const matchPhotos = sqliteTable("match_photos", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  matchId: integer("match_id").notNull(),
  r2Key: text("r2_key").notNull(),
  fileName: text("file_name").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  uploadedAt: text("uploaded_at").notNull().default(now),
});

export const documents = sqliteTable("documents", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  description: text("description"),
  category: text("category").notNull(),
  r2Key: text("r2_key").notNull(),
  fileName: text("file_name").notNull(),
  uploadedAt: text("uploaded_at").notNull().default(now),
  // Set when a member uploads this themselves (e.g. a cleanup-day discount
  // card) via the Phase 3 membership form; null for board-managed documents
  // like the range rules PDF.
  memberId: integer("member_id"),
  // Whether a board member has reviewed this upload. Defaults to 1 (already
  // reviewed) since board-managed uploads don't need review; the public
  // membership form explicitly inserts 0 for self-service uploads.
  reviewed: integer("reviewed").notNull().default(1),
});

export const MEMBER_STATUSES = [
  "Waiting List",
  "Non-Member",
  "Member",
  "Pending Review",
  "Terminated",
] as const;

export const members = sqliteTable("members", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  phone: text("phone"),
  address: text("address"),
  status: text("status").notNull().default("Member"), // one of MEMBER_STATUSES
  // A subset of Member -- shooting committee members are still regular
  // members (same status), just also on the committee. Independent of
  // status so recipient grouping can target the committee on top of, not
  // instead of, the Member group.
  onShootingCommittee: integer("on_shooting_committee").notNull().default(0),
  // Same idea as onShootingCommittee, but for the board -- board login
  // accounts live in the separate `admins` table, so this flag is what lets
  // a member's contact row be addressed as "Board" for recipient grouping.
  onBoard: integer("on_board").notNull().default(0),
  createdAt: text("created_at").notNull().default(now),
  // Digital signature on the Range Rules acknowledgement, from the Phase 3
  // membership form: the typed name and when they submitted it. Mirrors the
  // printed name / signature / NRA number fields on the legacy paper form.
  rulesAcknowledgedPrintedName: text("rules_acknowledged_printed_name"),
  rulesAcknowledgedName: text("rules_acknowledged_name"),
  rulesAcknowledgedAt: text("rules_acknowledged_at"),
  // Unique (like nmiCustomerVaultId/nmiSubscriptionId below) so two members
  // can't end up sharing an NRA number -- SQLite treats each NULL as
  // distinct under a UNIQUE constraint, so this doesn't block members who
  // haven't provided one yet.
  nraNumber: text("nra_number").unique(),
  // Opt-in consent to receive texts (board broadcasts and automated renewal
  // reminders) -- defaults to not-opted-in so no member is texted without a
  // recorded yes. smsOptInAt is the timestamp of the most recent opt-in (not
  // touched on opt-out), kept as evidence of consent if it's ever disputed.
  smsOptIn: integer("sms_opt_in").notNull().default(0),
  smsOptInAt: text("sms_opt_in_at"),
  // Cached result of the Veriphone carrier lookup (lib/veriphone.ts) for this
  // member's phone number, e.g. "Verizon Wireless" -- looked up once on first
  // send and reused after, since texts go out via each carrier's
  // email-to-SMS gateway (lib/sms.ts) rather than a shared SMS API, so the
  // gateway domain depends on knowing the carrier. Cleared if the phone
  // number changes (see app/api/admin/members) so a stale carrier can't send
  // to the wrong gateway.
  carrier: text("carrier"),
  // The shared annual dues cutoff (see lib/renewalCycle) this member has
  // paid through -- not a personal rolling anniversary. Set manually by a
  // board admin, or advanced automatically by lib/members.ts
  // recordDuesPayment right after a one-time charge succeeds (dues are never
  // auto-billed -- see the guardrail comment atop lib/nmi.ts). Drives the
  // 45- and 15-day-out renewal reminder texts and the annual termination
  // sweep, both keyed off this same cutoff.
  renewalDate: text("renewal_date"), // "YYYY-MM-DD"
  // The renewalDate value each reminder threshold has already been sent for,
  // so the daily cron job doesn't re-text the same renewal cycle.
  renewal45ReminderSentFor: text("renewal_45_reminder_sent_for"),
  renewal15ReminderSentFor: text("renewal_15_reminder_sent_for"),
  // Portal login (Phase 5). Null until the member sets up their own login via
  // the emailed setup link -- most existing rows predate the portal.
  passwordHash: text("password_hash"),
  salt: text("salt"),
  failedLoginCount: integer("failed_login_count").notNull().default(0),
  lockedUntil: integer("locked_until"), // epoch ms; login is blocked while this is in the future
  // Set once the member clicks the link from their verification email
  // (app/api/portal/verify-email). Signup lets someone pick any email
  // address directly with no proof of ownership -- this is what actually
  // confirms it, after the fact rather than gating account creation on it.
  emailVerified: integer("email_verified").notNull().default(0),
  // Legacy-only: rows written before the board's no-auto-billing decision
  // (see the guardrail comment atop lib/nmi.ts), back when a dues payment
  // created a recurring NMI subscription and stored the card on NMI's side.
  // Nothing writes these anymore -- app/api/payments/pay and
  // app/api/payments/invoice do a one-time, non-vaulted charge instead. Kept
  // around so app/api/admin/payments/cancel-legacy-subscriptions can find and
  // cancel any subscription still auto-charging at NMI; clears both fields
  // once cancelled.
  nmiCustomerVaultId: text("nmi_customer_vault_id").unique(),
  nmiSubscriptionId: text("nmi_subscription_id").unique(),
  subscriptionStatus: text("subscription_status"), // "active" once dues are paid for the current cutoff; set directly by the payment routes, not by a webhook
  // Admin-toggled once a new applicant's (status "Pending Review") background
  // check has been manually verified. Only meaningful pre-membership -- see
  // recomputeCanPay in lib/members.ts.
  backgroundCheckCleared: integer("background_check_cleared").notNull().default(0),
  // Whether this member's NRA proof is currently considered valid. Starts
  // true; flipped to false by the nightly NRA-expiration cron once
  // nraExpirationDate has passed, and only flipped back by admin review of
  // re-submitted proof (see app/portal/nra-expired) -- never auto-restored.
  nraActive: integer("nra_active").notNull().default(1),
  // "YYYY-MM-DD", entered on the public application and kept current via the
  // member portal profile form.
  nraExpirationDate: text("nra_expiration_date"),
  // Single derived flag every payment entry point checks (see
  // lib/members.ts recomputeCanPay) instead of re-deriving eligibility from
  // status/backgroundCheckCleared/nraActive at each checkpoint.
  canPay: integer("can_pay").notNull().default(0),
  // Set by the annual Sept 10 termination sweep (app/api/cron/renewal-termination)
  // when it soft-deletes a member for non-payment -- audit trail for the PII
  // scrub, since the row itself is kept (not hard-deleted) for payment history.
  terminatedAt: text("terminated_at"),
});

// One-time links for a member to set up their portal login or reset their
// password -- same dual-purpose pattern as passwordResetTokens above, just
// keyed to a member instead of an admin.
export const memberPasswordResetTokens = sqliteTable("member_password_reset_tokens", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  memberId: integer("member_id").notNull(),
  token: text("token").notNull().unique(),
  expiresAt: integer("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(now),
});

// One-time links proving a member controls the email address they signed up
// with. Separate from memberPasswordResetTokens (different purpose, and a
// member could otherwise use a still-valid reset link to sidestep this).
export const memberEmailVerificationTokens = sqliteTable("member_email_verification_tokens", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  memberId: integer("member_id").notNull(),
  token: text("token").notNull().unique(),
  expiresAt: integer("expires_at").notNull(),
  createdAt: text("created_at").notNull().default(now),
});

export const memberSessions = sqliteTable("member_sessions", {
  id: text("id").primaryKey(),
  memberId: integer("member_id").notNull(),
  expiresAt: integer("expires_at").notNull(),
});

// One row per successful NMI sale for member dues (first payment and every
// renewal alike, all one-time charges -- see the guardrail comment atop
// lib/nmi.ts). Rows are written by lib/members.ts recordDuesPayment right
// after app/api/payments/pay or app/api/payments/invoice gets a confirmed
// success back from NMI -- there's no webhook step, since a one-time sale
// has no async follow-up the way a subscription's recurring charge did.
export const payments = sqliteTable("payments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  memberId: integer("member_id").notNull(),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  paymentMethodType: text("payment_method_type"), // e.g. "card", "check"
  // NMI's transaction id -- present on every sale, so it doubles as this
  // table's idempotency key.
  nmiTransactionId: text("nmi_transaction_id").unique(),
  paidAt: text("paid_at").notNull().default(now),
});

export const emailCampaigns = sqliteTable("email_campaigns", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  subject: text("subject").notNull(),
  bodyHtml: text("body_html").notNull(),
  sentAt: text("sent_at").notNull().default(now),
  sentCount: integer("sent_count").notNull().default(0),
  failedCount: integer("failed_count").notNull().default(0),
  createdBy: text("created_by"),
  recipientEmail: text("recipient_email"), // set only for single-member sends; null means "all active members"
});

// One row per member a campaign was actually sent to, keyed to Resend's
// per-message id so the webhook (app/api/webhooks/resend) can match an
// open/click/bounce/spam event back to the right recipient. Column is still
// named postmark_message_id at the DB level (pre-dates the Resend switch) --
// only the TS-side name changed, so no migration was needed.
export const emailCampaignRecipients = sqliteTable("email_campaign_recipients", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  campaignId: integer("campaign_id").notNull(),
  memberId: integer("member_id"),
  email: text("email").notNull(),
  emailId: text("postmark_message_id"),
  sendError: text("send_error"),
  deliveredAt: text("delivered_at"),
  openedAt: text("opened_at"),
  clickedAt: text("clicked_at"),
  bouncedAt: text("bounced_at"),
  bounceType: text("bounce_type"), // e.g. Resend's bounce subType, "MailboxFull"
  spamComplaintAt: text("spam_complaint_at"),
});

// One row per invoice link emailed to a newly background-check-cleared
// applicant (app/api/admin/members/[id]) -- resolved by token on the public
// /membership/pay/[token] page so paying doesn't require a portal login.
// Same one-time-token-link pattern as memberPasswordResetTokens.
export const membershipInvoices = sqliteTable("membership_invoices", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  memberId: integer("member_id").notNull(),
  token: text("token").notNull().unique(),
  amountCents: integer("amount_cents").notNull().default(15000),
  createdAt: text("created_at").notNull().default(now),
  paidAt: text("paid_at"),
});

export const smsCampaigns = sqliteTable("sms_campaigns", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  body: text("body").notNull(),
  sentAt: text("sent_at").notNull().default(now),
  sentCount: integer("sent_count").notNull().default(0),
  failedCount: integer("failed_count").notNull().default(0),
  createdBy: text("created_by"),
  recipientPhone: text("recipient_phone"), // set only for single-member sends; null means "all contacts"
  // Public R2-backed URL of an attached picture, if any -- turns the send into
  // an MMS. Left in place (not deleted after sending) since carriers fetch it
  // asynchronously and the URL doubles as a record in send history.
  mediaUrl: text("media_url"),
});

// One row per member a text campaign was actually sent to. Texts now go out
// through each carrier's email-to-SMS gateway (lib/sms.ts) rather than
// SignalWire, so there's no per-message SID or delivery-status webhook
// anymore -- signalwireSid/status/deliveredAt/failedAt/errorCode stay
// populated only on rows from before that switch. gatewayEmail is the
// <number>@<carrier gateway> address the text was actually mailed to, kept
// for troubleshooting a bad send. Mirrors emailCampaignRecipients, minus the
// opens/clicks/spam-complaint fields SMS has no equivalent of.
export const smsCampaignRecipients = sqliteTable("sms_campaign_recipients", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  campaignId: integer("campaign_id").notNull(),
  memberId: integer("member_id"),
  phone: text("phone").notNull(),
  gatewayEmail: text("gateway_email"),
  signalwireSid: text("signalwire_sid"),
  sendError: text("send_error"),
  status: text("status"), // SignalWire's MessageStatus: queued/sending/sent/delivered/undelivered/failed
  deliveredAt: text("delivered_at"),
  failedAt: text("failed_at"),
  errorCode: text("error_code"),
});
